### ISSUE TITLE
Other Sources for Decorators :weary: 

### ISSUE THREAD

**Issue by ghost** [wycats/javascript-decorators#11]
Hi
I am looking for other sources to learn about decorators. The [_official_ proposal](https://github.com/tc39/ecma262) section on decorators links to this, of course, which is fine, but I find this guide only good for those that already understand annotations and just want to see how they would apply / look like in JavaScript.

For example

``` js
class Person {
  @readonly
  name() { return `${this.first} ${this.last}` }
}
```

Where is `@readonly` declared / defined? Is it a native directive the JavaScript interpreter is supposed to know or is it user defined? If it is the latter, what would be a possible implementation?

Also, `name()` is a method, so the point of making it `readonly` is to prevent :

``` js
let p = new Person(...)
p.name = /* another method | proxy method | undefined */
```

?

**Comment by jayphelps** [comment]
Decorators are user-defined functions that need to be in scope. i.e. you define them in the same scope or `import` them in. There are no proposed _built-in_ decorators.

The README does indeed give examples and explain how they work. In the case of `@readonly`, we can take the `@nonenumerable` example in the README and change it to mark the descriptor as `.writable = false`.

[Demo Using Babel.js](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20readonly%28target%2C%20key%2C%20descriptor%29%20%7B%0A%20%20descriptor.writable%20%3D%20false%3B%0A%20%20return%20descriptor%3B%0A%7D%0A%0Aclass%20Person%20%7B%0A%20%20%40readonly%0A%20%20name%28%29%20%7B%20return%20%60%24%7Bthis.first%7D%20%24%7Bthis.last%7D%60%20%7D%0A%7D%0A%0Avar%20dudebro%20%3D%20new%20Person%28%29%3B%0Adudebro.name%20%3D%20'Biblo%20Baggins'%3B%0A%2F%2F%20Cannot%20assign%20to%20read%20only%20property%20'name'%20of%20%5Bobject%20Object%5D&stage=0)

``` js
function readonly(target, key, descriptor) {
  descriptor.writable = false;
  return descriptor;
}

class Person {
  @readonly
  name() { return `${this.first} ${this.last}` }
}

var dudebro = new Person();
dudebro.name = 'Biblo Baggins';
// Cannot assign to read only property 'name' of [object Object]
```

**Comment by jayphelps** [comment]
You can also get inspiration from existing libraries that have started using decorators (using [Babel.js](https://babeljs.io/) to transpile).

One of which is mine (shameless plug): [core-decorators.js](https://github.com/jayphelps/core-decorators.js)

**Comment by ghost** [comment]
Thanks!
Are we talking about the same [README](https://github.com/wycats/javascript-decorators/blob/master/README.md)? I couldn't find the implementation of `readonly`.

Anyhow, I get it much better now :smile:  

I think the example would be just a bit more obvious if you gave the method another name like `fullName`. Even simpler would be using a property instead of a method, but I think you can't add annotations to properties or can you?

<hr>

About `core-decorators`

I see! 

``` js
 _extractFunctionSignature(fn) {
    return fn
      .toString()
      .replace(
        FUNCTION_REGEXP,
        (match, name = this.key, params) => name + params
      );
  }
```

Nice hack. So basically you parse the body of the function to extract the annotations. This occurs at compile time so there is no impact on performance, only waiting on your side, right?

**Comment by jayphelps** [comment]
@bucaran I imagine the reason @wycats didn't use class properties as examples is because they are separate proposals. ([class properties proposal](https://gist.github.com/jeffmo/054df782c05639da2adb))

It's important to note that decorators !== annotations. Decorators can actually change the descriptors itself where annotations are merely metadata, which something can later inspect and act on.

Babel.js allows you to use decorators on properties, but it's a very new feature so edge case bugs are still being worked out. Neither decorators or class properties are finalized, so keep that in mind. 

##### Regarding core-decorators

Decorators are runtime functions. They do not run at compile time; which isn't possible, if you think about what it means to "run code" at **compile** time. So there is indeed an impact on performance with any decorator you use, just like any other function invocation. In the case of `@override` in my library, I note in the README: 

> The idea is these decorators would be used to ensure code sanity, **but would be removed in production builds via a Babel plugin**.

Although such a plugin isn't written yet because I'm blocked on this [babel issue](https://github.com/babel/babel/issues/1244) and I also _just_ released that library the other day.

Make sense? :smiley:

**Comment by ghost** [comment]
Gotcha.

By _compile_ time I didn't mean _compile_ in the traditional sense, but I did use the word vaguely I guess. 

Now, I see there is obviously an impact on performance as the generated code from the one using annotations will have to configure properties at runtime, etc.

**Comment by jayphelps** [comment]
@bucaran If your questions are all answered, could you do us a solid and close this ticket? :smile:

Thanks!
