### ISSUE TITLE
decorator orders

### ISSUE THREAD

**Issue by otakustay** [wycats/javascript-decorators#20]
Suppose we have this code:

``` js
function foo(value) {
  return function (target, key, descriptor) {
    target.foo = value;
  };
}

class Base {
  @foo(3)
  @foo(4)
  bar() {

  }
}

let b = new Base();
console.log(b.foo);
```

What should be the output? `3` or `4`, or we just don't specify it in spec?

**Comment by sebmck** [comment]
3

On Sunday, 31 May 2015, Gray Zhang notifications@github.com wrote:

> Suppose we have this code:
> 
> function foo(value) {
>   return function (target, key, descriptor) {
>     target.foo = value;
>   };
> }
> class Base {
>   @foo(3)
>   @foo(4)
>   bar() {
> 
>   }
> }
> let b = new Base();console.log(b.foo);
> 
> What should be the output? 3 or 4, or we just don't specify it in spec?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/wycats/javascript-decorators/issues/20.

## 

Sebastian McKenzie

**Comment by sebmck** [comment]
To elaborate, decorators are evaluated bottomed. It's due to decorators
being function calls around the descriptor which means the inside gets
executed before the inside.

On Sunday, 31 May 2015, Gray Zhang notifications@github.com wrote:

> Closed #20 https://github.com/wycats/javascript-decorators/issues/20.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/wycats/javascript-decorators/issues/20#event-318213269
> .

## 

Sebastian McKenzie

**Comment by chocolateboy** [comment]
> which means the inside gets executed before the <s>inside</s> outside

Just stumbled across this LIFO surprise. Do any other languages reverse the (lexical) order of their decorators? [Python](http://simeonfranklin.com/blog/2012/jul/1/python-decorators-in-12-steps/)? wycats' awesome [Ruby prior art](http://yehudakatz.com/2009/07/11/python-decorators-in-ruby/)? [Perl](https://stackoverflow.com/questions/987059/how-do-perl-method-attributes-work)?

It seems really counterintuitive:

``` javascript
@foo(1)
@foo(2)
@foo(3)
method () {
    // ...
}
```

\- results in (babel++):

``` javascript
_createDecoratedClass(Foo, [{
    // ...
    decorators: [foo(3), foo(2), foo(1)],
    // ...
}]);
```

Is it too late to reconsider/fix this? What is the advantage of reversing the lexical, obvious (IMO), developer-specified order?

**Comment by loganfsmyth** [comment]
@chocolateboy Could you clarify which ordering you mean?

@sebmck I was curious since this comment did kind of surprise me. In Python for instance, while the decorator functions themselves are executed bottom-up as wrapper functions, the actual decorators are evaluated top-down as they are written. e.g.

```
let decorators = [];
decorators.unshift(foo(1));
decorators.unshift(foo(2));
decorators.unshift(foo(3));

_createDecoratedClass(Foo, [{
    // ...
    decorators: decorators,
    // ...
}]);
```

**Comment by chocolateboy** [comment]
> Could you clarify which ordering you mean?

I expected them to be applied in the order in which they're written i.e. I assumed:

``` javascript
@foo(1)
@foo(2)
@foo(3)
method () {
    // ...
}
```

would result in `foo` being called with 1, 2 and 3 (in that order):

``` javascript
foo(1)
foo(2)
foo(3)
```

**Comment by yuchi** [comment]
See [the desugared version](https://github.com/wycats/javascript-decorators#desugaring-es6-3). It becomes `F(G(original))`.

**Comment by chocolateboy** [comment]
@yuchi

Thanks. I see that's how it's specced, but I'm wondering what is the advantage of doing it that way?

**Comment by loganfsmyth** [comment]
@chocolateboy Decorators are applied bottom-up because they are thought of as wrapping around an existing method/descriptor, so conceptually they are applied to the thing below them, and if the thing below them is a decorator, then that decorator will get applied first.

```
class Base {
  @foo(3)
  @foo(4)
  bar() {

  }
}
```

is kind of like

```
class Base {}
Base.prototype.bar = foo(3)(foo(4)(function bar(){});
```

except working with descriptors instead of with functions directly. The outer one is basically overwriting the return value of the inner call.

**Comment by chocolateboy** [comment]
@loganfsmyth I appreciate that's how it's specced. I'm just questioning the rationale for the spec :-) I'm asking why this order is considered clearer, more sensible, more obvious, or less surprising than evaluating the decorator functions in the specified/lexical order.

I'm having to work around this ordering in decorator-related code and it feels hackish. It will be especially painful to do this if decorators have side effects...

Do any other decorator/attribute/annotation (may as well throw in Java/Groovy/Kotlin &c.) implementations execute in this (reverse) order?

Let's call the `foo` function that implements `@foo` the **outer** function and the `(target, name, descriptor) -> descriptor?` function it returns the **inner** function. If I'm reading [this](http://rbuckton.github.io/ReflectDecorators/typescript.html#proposal-decoratoreval) right, TypeScript executes ("evaluates") the outer functions top-down/FIFO and executes the inner functions bottom-up/LIFO. Babel is currently (5.8.3) executing the outer functions in [bottom-up order](https://github.com/wycats/javascript-decorators/issues/20#issuecomment-123556830). I'd prefer (and expect) both to execute in the lexical, top-down order, but at the very least would appreciate it if the outer functions, at least, were executed top-down.

Perhaps I should open a separate issue since this one is asking for clarification rather than discussing the rationale? Also, this issue is closed, but this is an active pain point for me in an otherwise wonderful proposal/feature. I imagine it will bite others down the line as more people use them.

**Comment by loganfsmyth** [comment]
@chocolateboy Gotcha, that's what I was trying to figure out with my first comment, but I think the wording of it ended up confusing and it was hard to tell. I agree with you that I think the decorator expressions are currently evaluated in the wrong order in Babel. I filed https://github.com/wycats/javascript-decorators/issues/28 to clarify that specifically since I think this issue is more specifically about the order execution for the decorator functions themselves are called.

**Comment by chocolateboy** [comment]
> I filed #28 to clarify that specifically since I think this issue is more specifically about the order execution for the decorator functions themselves are called.

Thanks. I spotted that after my post and have subscribed to it. I've created a [new issue](https://github.com/wycats/javascript-decorators/issues/29) to discuss the rationale.
