### ISSUE TITLE
Decorate method-parameters

### ISSUE THREAD

**Issue by tjoskar** [wycats/javascript-decorators#44]
I can't find any information about decorators for method-parameter, has this been addressed?

Example:

``` javascript
function bar(key) {
    return (prototype, name, argumentPosition) => {};
}

class Foo {
    method(@bar('some-key') param0) {} 
}
```

Desugaring (ES5):

``` javascript
var Foo = (function () {
  function Foo() {
  }
  Foo.prototype.bar = function () { }

  Foo = bar('some-key')(Foo.prototype, 'method', 0) || Foo;
  return Foo;
})();
```

This would give us the ability to use IoC:

Use case:

``` javascript
// inject.js
function resolve(Cls) {
    if (typeof Cls !== 'function') {
        return Cls;
    }
    if (!Array.isArray(Cls.inject)) {
        return new Cls();
    }
    const dependencies = Cls.inject.map(resolve);
    return new Cls(...dependencies);
}

function inject(injectable) {
    return (prototype, argumentPosition) => {
        prototype.inject = prototype.inject || [];
        prototype.inject[argumentPosition] = injectable;
    };
}

export {dependencyInjection, inject};
```

``` javascript
import fs from 'fs';
import {inject, resolve} from './inject';

class Foo {
    constructor(@inject(fs) fileSystem) {
         this.fs = fileSystem;
    }

    removeFile(path) {
        // some logic
        this.fs.unlink(path, err => {
            if (err) throw err;
            // doing something
        });
    }
}

// Using the class:
const foo = resolve(Foo);


// Testing
const foo = new Foo(mockFs); // no need for monkey patching `fs`
```

**Comment by bathos** [comment]
I'm probably missing something here, but I'm having trouble figuring out how the example given is not a very circuitous way to say:

``` js
class Foo {
  constructor(fileSystem=fs) {
    this.fs = fileSystem;
  }
}
```

Also, the inject property being appended in the sample is generic to the whole prototype, not the specific method, so does this mean the idea is that parameter decorators should be available only in constructors or is it just a peculiarity of this use case that the inject decorator is only concerned with constructors?

Edit:

Actually I don't think I understand any of this. Why would a parameter decorator be receiving the constructor's prototype but not the constructor, and not the property descriptor either? (Minor typo note: I think you meant to export 'resolve' instead of 'dependencyInjection' from inject.js)

**Comment by tjoskar** [comment]
Hi @bathos, 

Thanks for your feedback! 

You are absolutely right, my example is is the same as:

``` javascript
class Foo {
  constructor(fileSystem=fs) {
    this.fs = fileSystem;
  }
}
```

I don't know what I was thinking. This is clearly a immature proposal. 

Thanks! And sorry for my hasty idea.
